server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

logging:
  level:
    com: debug


mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml     #dao的实现
  config-location: classpath:/mybatis/mybatis.xml